org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=Necros
plugin_description=Discover the Necroland Dimension and its dungeons and creatures (Worldgen V2)
plugin_author=Legendary Workshop
plugin_website=
plugin_main_entrypoint=org.alex_hashtag.necros.Necros
server_version=2026.03.26-89796e57b

hytale.install_dir=E:/HytaleGameData

hytale.decompile_partial=true
